export const ingredientsInitialState = [
  { name: "Vodka", amount: 2000, amountType: "ml" },
  { name: "Cranberrys", amount: 150, amountType: "pcs" },
  { name: "Cointreau", amount: 130, amountType: "ml" },
  { name: "Cranberry juice", amount: 480, amountType: "ml" },
  { name: "Lime juice", amount: 460, amountType: "ml" },
  { name: "White rum", amount: 2160, amountType: "ml" },
  { name: "mint", amount: 52, amountType: "g" },

  { name: "Dark rum", amount: 460, amountType: "ml" },
  { name: "Orange Curacao", amount: 160, amountType: "ml" },
  { name: "Almond syrup", amount: 160, amountType: "ml" },
  { name: "Lime", amount: 115, amountType: "g" },
  { name: "Cachaca", amount: 60, amountType: "ml" },
  { name: "Tequila", amount: 960, amountType: "ml" },
  { name: "Triple sec", amount: 9460, amountType: "ml" },
  { name: "Coconut cream", amount: 60, amountType: "ml" },
  { name: "Pineapple juice", amount: 60, amountType: "ml" },

  { name: "Lemon juice", amount: 460, amountType: "ml" },
  { name: "Cola", amount: 860, amountType: "ml" },
  { name: "Ginger beer", amount: 560, amountType: "ml" },
  { name: "Prosecco", amount: 360, amountType: "ml" },
  { name: "Aperol", amount: 260, amountType: "ml" },
  { name: "Soda", amount: 560, amountType: "ml" },
  { name: "Cream", amount: 360, amountType: "ml" },
  { name: "Kahlua", amount: 460, amountType: "ml" },
  { name: "Gin", amount: 1160, amountType: "ml" },
];
